# Generated by Django 4.0.6 on 2022-10-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='college',
        ),
    ]
