# Generated by Django 4.0.6 on 2022-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_borrowedbook_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='current_level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=2000),
        ),
    ]
