# Generated by Django 4.0.6 on 2022-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_membership_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='department',
            field=models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Agricultural Economics', 'Agricultural Economics'), ('Agricultural Extension & Rural Development', 'Agricultural Extension & Rural Development'), ('Agriculture & Exosystem Engineering', 'Agriculture & Exosystem Engineering'), ('Animal Science', 'Animal Science'), ('Biochemistry', 'Biochemistry'), ('Business Administration', 'Business Administration'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Crop Science', 'Crop Science'), ('Economics', 'Economics'), ('Electrical and Information Engineering', 'Electrical and Information Engineering'), ('Food Science and Nutrition / Microbiology', 'Food Science and Nutrition / Microbiology'), ('Industrial Chemistry', 'Industrial Chemistry'), ('International Relations', 'International Relations'), ('Mass Communication', 'Mass Communication'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mechatronics Engineering ', 'Mechatronics Engineering'), ('Political Science', 'Political Science'), ('Sociology', 'Sociology'), ('Soil Science', 'Soil Science')], max_length=500, null=True),
        ),
    ]
