# Generated by Django 4.0.6 on 2022-10-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_membership_current_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='hall_block',
        ),
    ]
