# Generated by Django 4.0.6 on 2022-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_membership_hall_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='college',
            field=models.CharField(blank=True, choices=[('College of Pure and Applied Sciences', 'College of Pure and Applied Sciences'), ('College of Engineering', 'College of Engineering'), ('College of Business and Social Sciences', 'College of Business and Social Sciences'), ('College of Agricultural Sciences', 'College of Agricultural Sciences')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='current_level',
            field=models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='reg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='residence_hall',
            field=models.CharField(blank=True, choices=[('Abigail', 'Abigail'), ('Abraham', 'Abraham'), ('Daniel', 'Daniel'), ('Deborah', 'Deborah'), ('Dorcas', 'Dorcas'), ('Isaac', 'Isaac'), ('Daniel', 'Daniel'), ('Joseph', 'Joseph'), ('Sarah', 'Sarah')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='room',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
