# Generated by Django 4.0.6 on 2022-10-10 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_membership_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='location',
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
