# Generated by Django 4.0.6 on 2022-10-10 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_book_location_alter_membership_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_borrowed',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
