# Generated by Django 4.0.6 on 2022-10-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_borrowedbook_date_borrowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.membership')),
            ],
        ),
    ]
