# Generated by Django 4.0.6 on 2022-10-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_returncount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='unique_number',
            field=models.CharField(default='PSGL: ', max_length=1000),
        ),
    ]
