# Generated by Django 4.0.6 on 2022-10-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_copy_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='unique_number',
            field=models.CharField(max_length=1000),
        ),
    ]
